### ISSUE TITLE
Make compatible with smart-api

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/biolink-api#22]
Enter 

http://api.monarchinitiative.org/api/swagger.json

(or the equivalent on localhost:5000 if testing)

Into http://smart-api.info/editor/#/

And fix errors.

Once the errors are fixed, hit 'Save' - this registers the API.

It may get tedious to do this with every release, maybe there is a way to automate via github releases, can look into this later.

Note: the json is generated by the flaskrestplus framework, so the errors must be fixed at source. However, for debugging purposes we can edit the json

**Comment by cmungall** [comment]
> operation Ids must be unique. So, two get_association_search is not allowed

this is just a mistake in the python. Silent at the API level. Should be easy to fix

**Comment by cmungall** [comment]
you can't have two exact same names in the list for tags

```
tags:
 - name: default
   description: Default namespace
 - name: association
   description: Associations between entities or entity and descriptors
 - name: association
   description: Associations between entities or entity and descriptors
```

so dupes somewhere in the python
